project:
  type: website
  output-dir: docs

website:
  title: "Emil Kee-Ohl"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: files/cv.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
