project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Emil Kee-Tui"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
